services:
  maps-wrapper:
    build: .
    container_name: maps-wrapper
    env_file:
      - .env
    environment:
      - REDIS_HOST=maps_wrapper_cache
      - REDIS_PORT=6379
    depends_on:
      - maps_wrapper_cache

  maps_wrapper_cache:
    image: "redis:alpine"
    container_name: maps_wrapper_cache
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
